# Generated by Django 4.1.5 on 2023-03-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default='2023-03-12'),
            preserve_default=False,
        ),
    ]
