# Generated by Django 4.1.5 on 2023-04-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ticket_body_alter_ticket_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='states',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
