# Generated by Django 4.1.5 on 2023-04-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'low'), ('urgent', 'urgent')], default='low', max_length=100),
        ),
    ]
